name: Build llama.cpp CUDA MTP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Free disk space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo docker image prune -af || true

    - name: Install dependencies
      run: |
        sudo apt update

        sudo apt install -y \
          git \
          build-essential \
          cmake \
          ninja-build \
          wget \
          patchelf

    - name: Install CUDA 12.4
      run: |
        wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
    
        sudo dpkg -i cuda-keyring_1.1-1_all.deb
    
        sudo apt update
    
        sudo apt install -y cuda-toolkit-12-4


    - name: Checkout llama.cpp PR #22673
      run: |
        git clone https://github.com/ggml-org/llama.cpp.git
    
        cd llama.cpp
    
        git fetch origin pull/22673/head:pr-22673
    
        git checkout pr-22673

    - name: Build llama-server
      run: |
        export PATH=/usr/local/cuda/bin:$PATH

        nvcc --version
        cd llama.cpp

        cmake -B build \
          -G Ninja \
          -DCMAKE_BUILD_TYPE=Release \
          -DGGML_CUDA=ON \
          -DGGML_NATIVE=OFF \
          -DGGML_AVX=ON \
          -DGGML_AVX2=ON \
          -DGGML_F16C=ON \
          -DGGML_FMA=ON \
          -DGGML_AVX512=OFF \
          -DCMAKE_CUDA_ARCHITECTURES=61 \
          -DCUDA_USE_STATIC_CUDA_RUNTIME=ON

        cmake --build build \
          --config Release \
          --target llama-server llama-bench \
          -j$(nproc)

    - name: Package binaries
      run: |
        mkdir -p release
    
        cp llama.cpp/build/bin/llama-server release/
        cp llama.cpp/build/bin/llama-bench release/
    
        # copy llama.cpp generated libs
        find llama.cpp/build -name "*.so*" -exec cp {} release/ \;
    
        # copy CUDA runtime libs
        cp /usr/local/cuda/lib64/libcudart.so.12* release/
        cp /usr/local/cuda/lib64/libcublas.so.12* release/
        cp /usr/local/cuda/lib64/libcublasLt.so.12* release/
    
        chmod +x release/llama-server
    
        # add rpath
        patchelf --set-rpath '$ORIGIN' release/llama-server
        patchelf --set-rpath '$ORIGIN' release/llama-bench
    
        tar -czvf llama-server-mtp-cuda-ubuntu-avx2.tar.gz release
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: llama-server-mtp-cuda-avx2
        path: llama-server-mtp-cuda-ubuntu-avx2.tar.gz

    - name: Upload Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: latest
        files: llama-server-mtp-cuda-ubuntu-avx2.tar.gz
